apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: facturepro-frontend-hpa
  namespace: saas-africa
  labels:
    app: facturepro-frontend
    app.kubernetes.io/name: facturepro-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: facturepro-frontend
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: savanaflow-frontend-hpa
  namespace: saas-africa
  labels:
    app: savanaflow-frontend
    app.kubernetes.io/name: savanaflow-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: savanaflow-frontend
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: schoolflow-frontend-hpa
  namespace: saas-africa
  labels:
    app: schoolflow-frontend
    app.kubernetes.io/name: schoolflow-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: schoolflow-frontend
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
